name: Build Pull Request and Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build Geyser
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: geyser

      # 以下artifact上传步骤保持不变...
      - name: Archive artifacts (Geyser Fabric)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser Fabric
          path: bootstrap/fabric/build/libs/Geyser-Fabric.jar
      - name: Archive artifacts (Geyser Standalone)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser Standalone
          path: bootstrap/standalone/build/libs/Geyser-Standalone.jar
      - name: Archive artifacts (Geyser Spigot)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser Spigot
          path: bootstrap/spigot/build/libs/Geyser-Spigot.jar
      - name: Archive artifacts (Geyser BungeeCord)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser BungeeCord
          path: bootstrap/bungeecord/build/libs/Geyser-BungeeCord.jar
      - name: Archive artifacts (Geyser Sponge)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser Sponge
          path: bootstrap/sponge/build/libs/Geyser-Sponge.jar
      - name: Archive artifacts (Geyser Velocity)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Geyser Velocity
          path: bootstrap/velocity/build/libs/Geyser-Velocity.jar
